# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calisanekran.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_calisanekran(object):
    def setupUi(self, calisanekran):
        calisanekran.setObjectName("calisanekran")
        calisanekran.resize(884, 617)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/NicePng_table-clipart-png_8386405.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        calisanekran.setWindowIcon(icon)
        calisanekran.setStyleSheet("#calisanekran {\n"
"border-image: url(:/icons/icons/Pngtree—modern industrial factory_5418694.png);\n"
"}")
        self.horizontalLayoutWidget = QtWidgets.QWidget(calisanekran)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(450, 30, 351, 281))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.pb_cmakinaislem = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_cmakinaislem.sizePolicy().hasHeightForWidth())
        self.pb_cmakinaislem.setSizePolicy(sizePolicy)
        self.pb_cmakinaislem.setMinimumSize(QtCore.QSize(50, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pb_cmakinaislem.setFont(font)
        self.pb_cmakinaislem.setStyleSheet("background-color: rgb(111, 111, 111);\n"
"color: rgb(238, 119, 15);\n"
"border -radius : 5px")
        self.pb_cmakinaislem.setIconSize(QtCore.QSize(25, 25))
        self.pb_cmakinaislem.setObjectName("pb_cmakinaislem")
        self.verticalLayout.addWidget(self.pb_cmakinaislem)
        spacerItem2 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.pb_canaekrandon = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_canaekrandon.sizePolicy().hasHeightForWidth())
        self.pb_canaekrandon.setSizePolicy(sizePolicy)
        self.pb_canaekrandon.setMinimumSize(QtCore.QSize(50, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pb_canaekrandon.setFont(font)
        self.pb_canaekrandon.setStyleSheet("background-color: rgb(111, 111, 111);\n"
"color: rgb(238, 119, 15);\n"
"border -radius : 5px")
        self.pb_canaekrandon.setIconSize(QtCore.QSize(25, 25))
        self.pb_canaekrandon.setObjectName("pb_canaekrandon")
        self.verticalLayout.addWidget(self.pb_canaekrandon)
        spacerItem3 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)

        self.retranslateUi(calisanekran)
        QtCore.QMetaObject.connectSlotsByName(calisanekran)

    def retranslateUi(self, calisanekran):
        _translate = QtCore.QCoreApplication.translate
        calisanekran.setWindowTitle(_translate("calisanekran", "Form"))
        self.pb_cmakinaislem.setText(_translate("calisanekran", "Makina İşlemleri"))
        self.pb_canaekrandon.setText(_translate("calisanekran", "Ana Ekrana Dön"))
import icons_rc
